application:
  title: "Hurr - API"
  version: "1.0.0"

spring:

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hurr?currentSchema=hurr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 58495673570-raok2adfrlt76dfjivrb53rc3j9l4928.apps.googleusercontent.com
            clientSecret: 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

  mail:
    host: smtp.gmail.com
    port: 587
    username: edersonsergiocoelho@gmail.com
    password: jyfbeilm hwvv snmr
    #password: xfdjrdsrpfgucbms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:8081/oauth2/redirect
      - http://localhost:4200/
      - http://localhost:4200/user/login
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect