# Configurações gerais da aplicação
application:
  title: "Hurr - API"  # Título da aplicação
  version: "0.0.1"  # Versão da aplicação

# Configurações dos scripts que a aplicação pode executar
scripts:
  generic:
    enabled: true  # Habilita a execução de scripts genéricos
  test:
    enabled: true  # Habilita a execução de scripts de teste
  path: sql  # Caminho onde os scripts SQL estão localizados

spring:

  # Configurações do DataSource (Banco de Dados)
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hurr?currentSchema=hurr}  # URL do banco de dados PostgreSQL
    username: ${DB_USERNAME:postgres}  # Nome de usuário do banco de dados
    password: ${DB_PASSWORD:postgres}  # Senha do banco de dados
    driver-class-name: org.postgresql.Driver  # Driver do banco de dados

  # Configurações do JPA (Java Persistence API)
  jpa:
    show-sql: true  # Exibe as consultas SQL no console
    open-in-view: false  # Desativa a sessão do Hibernate na visualização
    properties:
      hibernate:
        format_sql: true  # Formata as consultas SQL para fácil leitura

  # Configurações de Segurança
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}  # ID do cliente do Google
            clientSecret: ${GOOGLE_CLIENT_SECRET}  # Segredo do cliente do Google

  # Configurações do Servlet
  servlet:
    multipart:
      max-file-size: 10MB  # Tamanho máximo do arquivo de upload
      max-request-size: 10MB  # Tamanho máximo da requisição

  # Configurações de Email
  mail:
    host: smtp.gmail.com  # Host do servidor de email
    port: 587  # Porta do servidor de email
    username: ${MAIL_USERNAME}  # Nome de usuário para autenticação
    password: ${MAIL_PASSWORD}  # Senha para autenticação
    properties:
      mail:
        smtp:
          auth: true  # Habilita autenticação SMTP
          starttls:
            enable: true  # Habilita STARTTLS para conexão segura

  # Configurações do Flyway (migrador de banco de dados)
  flyway:
    enabled: true  # Habilita o Flyway para gerenciar migrações de banco de dados
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    root: INFO  # Nível padrão de log para a aplicação
    org.springframework: INFO  # Log detalhado para o Spring Framework
    org.flywaydb: INFO  # Log detalhado para operações do Flyway
    br.com.escconsulting: INFO  # Log detalhado para o pacote específico da sua aplicação

# Configurações para integração com Mercado Pago
mercado.pago:
  access.token: ${MERCADO_PAGO_TOKEN}

# Configurações para integração com o Inter (banco)
inter:
  client:
    id: ${INTER_CLIENT_ID}  # ID do cliente do Inter
    secret: ${INTER_CLIENT_SECRET}  # Segredo do cliente do Inter
  cert:
    path: ${INTER_CERT_PATH}  # Caminho para o certificado PFX
    password: ${INTER_CERT_PASSWORD}  # Senha do certificado PFX

# Configurações para integração com Telegram
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}  # Token do bot do Telegram

# Configurações para Twilio (serviço de mensagens)
twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}  # SID da conta Twilio
  auth:
    token: ${TWILIO_AUTH_TOKEN}  # Token de autenticação Twilio
  phone:
    number: ${TWILIO_PHONE_NUMBER}  # Número de telefone Twilio
    whatsapp: ${TWILIO_WHATSAPP_NUMBER}  # Número de WhatsApp Twilio

# Configurações para WhatsApp
whatsapp:
  access.token: ${WHATSAPP_ACCESS_TOKEN}  # Token de acesso para WhatsApp
  from.phone.number.id: ${WHATSAPP_PHONE_NUMBER_ID}  # ID do número de telefone WhatsApp

# Configurações da aplicação
app:
  auth:
    tokenSecret: ${AUTH_TOKEN_SECRET}  # Segredo para assinar tokens de autenticação
    tokenExpirationMsec: ${AUTH_TOKEN_EXPIRATION_MS:864000000}  # Expiração do token em milissegundos (10 dias)

  oauth2:
    authorizedRedirectUris:  # URIs para redirecionamento após autenticação
      - http://localhost:8081/oauth2/redirect  # URI para redirecionamento local
      - http://localhost:4200/  # URI para redirecionamento do frontend
      - http://localhost:4200/user/login  # URI de login
      - myandroidapp://oauth2/redirect  # URI para redirecionamento no Android
      - myiosapp://oauth2/redirect  # URI para redirecionamento no iOS
