application:
  title: "Hurr - API"
  version: "1.0.0"

spring:

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hurr?currentSchema=hurr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 58495673570-raok2adfrlt76dfjivrb53rc3j9l4928.apps.googleusercontent.com
            clientSecret: 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

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: edersonsergiocoelho@gmail.com
    password: jyfbeilm hwvv snmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true

telegram:
  bot:
    token: 6763877962:AAElA1aQ8FlaOvZjeStegxm41PQUbKRxJ6M

twilio:
  account:
    sid: ACb5e993772f05ca517d681c993a7969cb
  auth:
    token: e45a50438c256c1d2cd05e4308bee3e9
  phone:
    number: "+18329242707"
    whatsapp: "+14155238886"

whatsapp:
  #access.token: EAAak18SW4KoBOZCsePbyNqVNukpKNQbNFk1Pr0FnUFGUK9be4TvUvmbBSlOWpdeeXUjISYkYESbvGZCOCYwZBi4oNis1LsB93DwG12vGK0VrWKOZBuDGimBf5mbR1ZAzze2cfkFE6H3DxXDZAyiaCkgT2AlHHZBMl39LbtKyZCxEFj1FOUyqZBBFIDKo7UA6frGZBM
  access.token: EAAak18SW4KoBOyHh15Gl4iiz73QX7f7Ldi64bXy06SIZA4axZA4ae1qNxLGYzYvfIjBBz2g9cetNlCGCVA8FMQdKzK4CvhHwaPjURuiZABU89iyah2TZAYOUbE1SHz44BZCwVzdu4Coa9Iq1znzLnkt0dfSSxkDkPqUR4yFhdZA2qZASNmIrGuQJ06ZAFxIZCc2waVWlPQtW412ujeZBw4
  from.phone.number.id: 223267017528976

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:8081/oauth2/redirect
      - http://localhost:4200/
      - http://localhost:4200/user/login
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect