SET search_path TO hurr;

INSERT INTO country (country_name, country_code) VALUES ('Afeganistão', 'AF') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('África do Sul', 'ZA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Albânia', 'AL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Alemanha', 'DE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Andorra', 'AD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Angola', 'AO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Argentina', 'AR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Armênia', 'AM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Austrália', 'AU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Áustria', 'AT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Azerbaijão', 'AZ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bahamas', 'BS') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bahrein', 'BH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bangladesh', 'BD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Barbados', 'BB') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bélgica', 'BE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Belize', 'BZ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Benin', 'BJ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bolívia', 'BO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bósnia e Herzegovina', 'BA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Botsuana', 'BW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Brasil', 'BR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Brunei', 'BN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Bulgária', 'BG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Burkina Faso', 'BF') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Burúndi', 'BI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Butão', 'BT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Cabo Verde', 'CV') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Camarões', 'CM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Canadá', 'CA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Catar', 'QA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Chile', 'CL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('China', 'CN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Chipre', 'CY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Colômbia', 'CO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Comores', 'KM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Congo', 'CG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Congo, República Democrática do', 'CD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Coreia do Norte', 'KP') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Coreia do Sul', 'KR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Costa do Marfim', 'CI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Costa Rica', 'CR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Croácia', 'HR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Cuba', 'CU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Dinamarca', 'DK') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Djibuti', 'DJ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Dominica', 'DM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Egito', 'EG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('El Salvador', 'SV') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Emirados Árabes Unidos', 'AE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Equador', 'EC') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Eritreia', 'ER') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Eslováquia', 'SK') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Eslovênia', 'SI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Espanha', 'ES') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Estados Unidos', 'US') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Estônia', 'EE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Etiópia', 'ET') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Fiji', 'FJ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Filipinas', 'PH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Finlândia', 'FI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('França', 'FR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Gabão', 'GA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Gâmbia', 'GM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Gana', 'GH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Gibraltar', 'GI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Grécia', 'GR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Granada', 'GD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Guiné', 'GN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Guiné-Bissau', 'GW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Guiné Equatorial', 'GQ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Guyana', 'GY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Haiti', 'HT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Honduras', 'HN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Hong Kong', 'HK') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Hungria', 'HU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Iémen', 'YE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Ilhas Marshall', 'MH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Ilhas Maurício', 'MU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Ilhas Salomão', 'SB') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Índia', 'IN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Indonésia', 'ID') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Irã', 'IR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Iraque', 'IQ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Irlanda', 'IE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Islândia', 'IS') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Israel', 'IL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Itália', 'IT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Jamaica', 'JM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Japão', 'JP') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Jordânia', 'JO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Kiribati', 'KI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Kuwait', 'KW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Laos', 'LA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Líbano', 'LB') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Libéria', 'LR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Líbia', 'LY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Liechtenstein', 'LI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Lituânia', 'LT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Luxemburgo', 'LU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Madagascar', 'MG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Malásia', 'MY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Malawi', 'MW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Maldivas', 'MV') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Mali', 'ML') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Malta', 'MT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Marrocos', 'MA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Mauritânia', 'MR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('México', 'MX') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Mianmar', 'MM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Moldávia', 'MD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Mônaco', 'MC') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Mongólia', 'MN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Montenegro', 'ME') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Namíbia', 'NA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nauru', 'NR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nepal', 'NP') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nicarágua', 'NI') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Níger', 'NE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nigéria', 'NG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Noruega', 'NO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nova Caledônia', 'NC') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Nova Zelândia', 'NZ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Omã', 'OM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Países Baixos', 'NL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Palau', 'PW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Panamá', 'PA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Papua Nova Guiné', 'PG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Paquistão', 'PK') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Paraguai', 'PY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Peru', 'PE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Polônia', 'PL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Porto Rico', 'PR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Portugal', 'PT') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Quênia', 'KE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('República Centro-Africana', 'CF') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('República Dominicana', 'DO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Romênia', 'RO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Ruanda', 'RW') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Rússia', 'RU') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Saara Ocidental', 'EH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Saint Vincent e Granadinas', 'VC') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Samoa', 'WS') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('San Marino', 'SM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Santa Lúcia', 'LC') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('São Cristóvão e Neves', 'KN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('São Tomé e Príncipe', 'ST') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Senegal', 'SN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Serra Leoa', 'SL') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Sérvia', 'RS') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Síria', 'SY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Singapura', 'SG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Somália', 'SO') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Sri Lanka', 'LK') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Suazilândia', 'SZ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Sudão', 'SD') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Suriname', 'SR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Suécia', 'SE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Suíça', 'CH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Tadjiquistão', 'TJ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Tailândia', 'TH') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Timor-Leste', 'TL') ON CONFLICT (country_code) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Tunísia', 'TN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Turcomenistão', 'TM') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Turquia', 'TR') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Tuvalu', 'TV') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Uganda', 'UG') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Ucrânia', 'UA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Uruguai', 'UY') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Uzbequistão', 'UZ') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Vaticano', 'VA') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Venezuela', 'VE') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Vietnam', 'VN') ON CONFLICT (country_name) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Zâmbia', 'ZM') ON CONFLICT (country_code) DO NOTHING;
INSERT INTO country (country_name, country_code) VALUES ('Zimbábue', 'ZW') ON CONFLICT (country_name) DO NOTHING;